#!/bin/bash

# Configuration
UTILITY_NAME="NeXdocMan"
SCRIPT_FILE_NAME=$(basename "$0")
SCRIPT_NAME=$(basename "$0" .sh)
VERSION="v2.3"
UTILITY_DIR=${UTILITY_DIR:-"$(dirname "$(realpath "$0")")"}
LOG_DIR="/var/log/$UTILITY_NAME"
LOG_FILE="$LOG_DIR/${SCRIPT_NAME}.log"
SYSTEM_DIR="/usr/local/lib/nexdocman"
CFG_FILE="$SYSTEM_DIR/${SCRIPT_NAME}.cfg"

# Global variables
AUTO_YES=false
VERBOSE=false
ACTUAL_USER="${SUDO_USER:-$(whoami)}"
REFRESHED=${REFRESHED:-false}

# Default Config values
ENABLE_AUTO_CLEANUP=true
CLEANUP_CRON="0 3 */2 * *"
LOG_LEVEL="INFO"
LOGPRUNE_ENABLED=true
LOGPRUNE_MAX_AGE_DAYS=7

# Load config if exists
if [ -f "$CFG_FILE" ]; then
    source "$CFG_FILE"
fi

# Helper to check log level
level_to_num() {
    case "$1" in
        DEBUG) echo 0 ;;
        INFO) echo 1 ;;
        WARNING) echo 2 ;;
        ERROR) echo 3 ;;
        *) echo 1 ;;
    esac
}

log_message() {
    local level="INFO"
    local message="$1"

    if [[ "$message" =~ ^\[(DEBUG|INFO|WARNING|ERROR)\](.*) ]]; then
        filter_level="${BASH_REMATCH[1]}"
    else
        filter_level="INFO"
    fi

    local current_level_num=$(level_to_num "${LOG_LEVEL:-INFO}")
    local msg_level_num=$(level_to_num "$filter_level")

    if [ "$msg_level_num" -ge "$current_level_num" ]; then
        local formatted_msg="[$(date '+%Y-%m-%d %H:%M:%S')] [$SCRIPT_NAME $VERSION] ${message}"
        echo "$formatted_msg" | sudo tee -a "$LOG_FILE" >/dev/null
        
        if [ -t 1 ]; then
            echo "${message}"
        fi
    fi
}

run_command() {
    local temp_out
    temp_out=$(mktemp)
    
    if [ "$VERBOSE" = true ]; then
        "$@" 2>&1 | tee "$temp_out"
    else
        "$@" > "$temp_out" 2>&1
    fi
    local exit_code=${PIPESTATUS[0]}
    
    if [ "$(level_to_num "$LOG_LEVEL")" -le 0 ]; then
        log_message "[DEBUG] Executing: $*"
        while IFS= read -r line; do
            [ -n "$line" ] && log_message "[DEBUG]   $line"
        done < "$temp_out"
    fi
    rm -f "$temp_out"
    return $exit_code
}

setup_dirs() {
    if [ ! -d "$LOG_DIR" ]; then
        sudo mkdir -p "$LOG_DIR"
        sudo chmod 755 "$LOG_DIR"
        sudo chown root:root "$LOG_DIR"
    fi
    if [ ! -f "$LOG_FILE" ]; then
        sudo touch "$LOG_FILE"
        sudo chmod 644 "$LOG_FILE"
        sudo chown root:root "$LOG_FILE"
    fi
}

create_default_config() {
    if [ ! -f "$CFG_FILE" ]; then
        sudo mkdir -p "$SYSTEM_DIR"
        sudo chmod 755 "$SYSTEM_DIR"
        sudo chown root:root "$SYSTEM_DIR"
        
        sudo bash -c "cat > $CFG_FILE" <<EOF
# ==============================================================================
# $UTILITY_NAME Configuration File
# Auto-generated by $SCRIPT_FILE_NAME ($VERSION)
# ==============================================================================

ENABLE_AUTO_CLEANUP=true
CLEANUP_CRON="0 3 */2 * *"
LOG_LEVEL="INFO"
LOGPRUNE_ENABLED=true
LOGPRUNE_MAX_AGE_DAYS=7
EOF
        sudo chmod 644 "$CFG_FILE"
        log_message "[INFO] Default configuration created at $CFG_FILE"
    fi
}

show_versions() {
    echo "$UTILITY_NAME $VERSION"
}

show_help() {
    echo "========================================================================="
    echo " 🐧 $UTILITY_NAME ($VERSION) - Intelligent Docker Orchestrator"
    echo "========================================================================="
    echo ""
    echo "USAGE:"
    echo "  $SCRIPT_NAME [OPTIONS]"
    echo ""
    echo "DESCRIPTION:"
    echo "  $UTILITY_NAME is an intelligent manager for Docker and Docker Compose."
    echo "  It handles installation, updates, scheduled system pruning, and"
    echo "  comprehensive teardowns."
    echo ""
    echo "OPTIONS:"
    echo "  [General]"
    echo "  -h, --help           Show this comprehensive help message and exit."
    echo "  -v, --version        Show utility and script version."
    echo "  -y, --yes            Auto-confirm all prompts (Non-interactive mode)."
    echo "  -V, --verbose        Run operations with verbose output to terminal."
    echo ""
    echo "  [Deployment & Removal]"
    echo "  -d, --deploy         Initialize directories, config, and deploy $UTILITY_NAME globally."
    echo "  -r, --remove         Uninstall $UTILITY_NAME, its logs, configs, and schedules entirely."
    echo ""
    echo "  [Docker Operations]"
    echo "  -i, --install        Install Docker and Docker Compose and set up groups."
    echo "  -m, --manage         Check for Docker and Compose updates and apply them."
    echo "  -k, --check-images   Audit local Docker images for remote updates (Read-only)."
    echo "  -u, --update-images  Audit local Docker images and pull available updates."
    echo "  -c, --cleanup        Manually trigger a deep Docker system prune."
    echo "  -C, --configure-cron Reload the automated prune schedule from $CFG_FILE."
    echo "  -p, --purge          Completely uninstall Docker, Compose, and wipe all data."
    echo ""
    echo "EXAMPLES:"
    echo "  sudo $SCRIPT_NAME -d              # First-time setup on a new server"
    echo "  sudo $SCRIPT_NAME -i -y           # Install Docker cleanly with no prompts"
    echo "  $SCRIPT_NAME -c                   # Trigger an immediate runtime prune"
    echo "  $SCRIPT_NAME -r -y                # Uninstall $UTILITY_NAME but leave Docker running"
    echo "  sudo $SCRIPT_NAME -p -y           # Nuke and pave the Docker system silently"
    echo ""
    echo "For advanced configuration (scheduling, log levels), edit: $CFG_FILE"
}

setup_cron() {
    if [[ "$ENABLE_AUTO_CLEANUP" == "true" || "$ENABLE_AUTO_CLEANUP" == true ]]; then
        local cron_cmd="$CLEANUP_CRON /usr/local/bin/$SCRIPT_NAME --cleanup >> /var/log/$UTILITY_NAME/cron.log 2>&1"
        local current_crontab
        current_crontab=$(sudo crontab -l 2>/dev/null || true)
        
        local new_crontab=$(echo "$current_crontab" | grep -vF "/usr/local/bin/$SCRIPT_NAME --cleanup")
        new_crontab+=$'\n'"$cron_cmd"
        
        if ! echo "$current_crontab" | grep -qF "$cron_cmd"; then
            log_message "[INFO] Updating crontab with automatic cleanup schedule ($CLEANUP_CRON)..."
            echo "$new_crontab" | sudo crontab -
            log_message "[INFO] SUCCESS: Cron setup complete."
        else
            log_message "[INFO] Cron job for automatic cleanup is already up to date."
        fi
    else
        local current_crontab
        current_crontab=$(sudo crontab -l 2>/dev/null || true)
        if echo "$current_crontab" | grep -qF "/usr/local/bin/$SCRIPT_NAME --cleanup"; then
            local new_crontab=$(echo "$current_crontab" | grep -vF "/usr/local/bin/$SCRIPT_NAME --cleanup")
            echo "$new_crontab" | sudo crontab -
            log_message "[INFO] Automated cleanup is disabled in config. Removed from crontab."
        fi
    fi
}

install_utility() {
    setup_dirs
    create_default_config
    
    sudo cp -v "$(realpath "$0")" "/usr/local/bin/$SCRIPT_NAME" 2>&1 | while read -r line; do log_message "[INFO] $line"; done
    if [ ${PIPESTATUS[0]} -ne 0 ]; then
        log_message "[ERROR] Failed to copy script to /usr/local/bin/$SCRIPT_NAME"
        exit 1
    fi
    sudo chmod +x "/usr/local/bin/$SCRIPT_NAME"
    
    if [ -f "/usr/local/bin/$SCRIPT_FILE_NAME" ]; then
        sudo rm -f "/usr/local/bin/$SCRIPT_FILE_NAME"
    fi
    
    if [ -f "/usr/local/bin/$SCRIPT_NAME" ] && [ -x "/usr/local/bin/$SCRIPT_NAME" ]; then
        log_message "[INFO] SUCCESS: Verified: /usr/local/bin/$SCRIPT_NAME exists and is executable"
        log_message "[INFO] Utility installed to /usr/local/bin/$SCRIPT_NAME. Run '$SCRIPT_NAME' to start."
        
        local orig_path
        orig_path=$(realpath "$0")
        if [[ "$orig_path" != "/usr/local/bin/"* ]]; then
            log_message "[INFO] Removing deployment payload: $orig_path"
            sudo rm -f "$orig_path"
        fi
    else
        log_message "[ERROR] /usr/local/bin/$SCRIPT_NAME does not exist or is not executable"
        exit 1
    fi
}

uninstall_utility() {
    log_message "[INFO] Preparing to uninstall $UTILITY_NAME..."
    
    if [ "$AUTO_YES" = false ]; then
        log_message "[WARNING] This will remove $UTILITY_NAME, its logs, configuration, and scheduled cron jobs."
        log_message "[WARNING] Docker and Docker Compose will NOT be modified."
        read -p "[WARNING] Type 'YES' to continue uninstalling the utility: " confirm
        [[ "$confirm" != "YES" ]] && { log_message "[INFO] Uninstall cancelled."; return 0; }
    fi

    log_message "[INFO] Removing Crontab entries..."
    local current_crontab
    current_crontab=$(sudo crontab -l 2>/dev/null || true)
    if echo "$current_crontab" | grep -qF "/usr/local/bin/$SCRIPT_NAME --cleanup"; then
        local new_crontab=$(echo "$current_crontab" | grep -vF "/usr/local/bin/$SCRIPT_NAME --cleanup")
        echo "$new_crontab" | sudo crontab -
        log_message "[INFO] Automated cleanup schedule removed from Crontab."
    fi

    log_message "[INFO] Removing configuration files..."
    if [ -d "$SYSTEM_DIR" ]; then
        sudo rm -rf "$SYSTEM_DIR"
        log_message "[INFO] System directory $SYSTEM_DIR removed."
    fi

    echo "$(date '+%Y-%m-%d %H:%M:%S') [INFO] Removing log files..."
    if [ -d "$LOG_DIR" ]; then
        sudo rm -rf "$LOG_DIR"
        echo "$(date '+%Y-%m-%d %H:%M:%S') [INFO] Log directory $LOG_DIR removed."
    fi

    echo "$(date '+%Y-%m-%d %H:%M:%S') [INFO] SUCCESS: $UTILITY_NAME configuration, schedules, and logs have been removed."
    echo "$(date '+%Y-%m-%d %H:%M:%S') [INFO] Removing script binary..."
    sudo rm -f "/usr/local/bin/$SCRIPT_NAME"
    echo "$(date '+%Y-%m-%d %H:%M:%S') [INFO] Uninstall complete."
    exit 0
}

# MODULE: CLEANUP & LOG MANAGEMENT
manage_logs() {
    if [[ "$LOGPRUNE_ENABLED" != "true" && "$LOGPRUNE_ENABLED" != true ]]; then
        log_message "[INFO] Log pruning is disabled in config. Skipping."
        return 0
    fi

    if [ ! -f "$LOG_FILE" ] || [ ! -s "$LOG_FILE" ]; then 
        return 0
    fi

    local max_days="${LOGPRUNE_MAX_AGE_DAYS:-7}"
    local CUTOFF_STRING
    CUTOFF_STRING=$(LC_ALL=C date -d "$max_days days ago" '+%Y-%m-%d %H:%M:%S' 2>/dev/null)
    
    if [ -z "$CUTOFF_STRING" ]; then
        log_message "[ERROR] Failed to calculate cutoff date for log management."
        return 0
    fi

    local TEMP_FILE=$(mktemp)

    LC_ALL=C awk -v cutoff_str="$CUTOFF_STRING" '
    {
        if (match($0, /^\[([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})\]/)) {
            timestamp = substr($0, 2, 19)
            if (timestamp >= cutoff_str) {
                print $0
                keep = 1
            } else {
                keep = 0
            }
        } else {
            if (keep == 1 || keep == "") {
                print $0
            }
        }
    }' "$LOG_FILE" > "$TEMP_FILE"

    if [ ! -s "$TEMP_FILE" ] && [ -s "$LOG_FILE" ]; then
        log_message "[WARNING] Log pruning resulted in an empty file. Keeping original log."
        rm -f "$TEMP_FILE"
        return 0
    fi

    local lines_before=$(wc -l < "$LOG_FILE")
    local lines_after=$(wc -l < "$TEMP_FILE")
    local lines_pruned=$((lines_before - lines_after))

    sudo mv "$TEMP_FILE" "$LOG_FILE"
    sudo chmod 644 "$LOG_FILE"
    
    if [ "$lines_pruned" -gt 0 ]; then
        log_message "[INFO] Pruned $lines_pruned log lines older than $max_days days."
    fi
}

perform_cleanup() {
    log_message "[INFO] Performing a comprehensive system prune..."
    if ! command -v docker &>/dev/null; then
        log_message "[WARNING] Docker is not installed. Skipping cleanup."
        return 0
    fi
    
    local prune_output
    prune_output=$(sudo docker system prune -a --volumes -f 2>&1)
    
    local reclaimed
    reclaimed=$(echo "$prune_output" | grep "Total reclaimed space:" | sed 's/Total reclaimed space: //')
    
    local deleted_count
    deleted_count=$(echo "$prune_output" | grep -cE "^(deleted:|untagged:)")
    
    if [ "$(level_to_num "$LOG_LEVEL")" -le 0 ]; then
        log_message "[DEBUG] Raw Prune Dump Start:"
        echo "$prune_output" | while IFS= read -r line; do
            if [ -n "$line" ]; then
                log_message "[DEBUG]   $line"
            fi
        done
        log_message "[DEBUG] Raw Prune Dump End."
    fi

    if [ -n "$reclaimed" ]; then
        log_message "[INFO] PRUNE SUMMARY: Pruned $deleted_count items. Total reclaimed space: $reclaimed."
        log_message "[INFO] SUCCESS: Comprehensive system prune completed."
    else
        log_message "[ERROR] Prune completed but failed to parse reclaimed space."
    fi
    
    manage_logs
}

# MODULE: SETUP (Install Docker & Compose)
setup_docker() {

    log_message "[INFO] Checking for older conflicting Docker packages..."
    for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do
        sudo apt-get purge -y $pkg >/dev/null 2>&1 || true
    done
    log_message "[INFO] Conflicting packages resolved."

    log_message "[INFO] Checking for Docker..."
    if ! command -v docker &>/dev/null; then
        log_message "[INFO] Installing Docker and Compose..."
        
        local fetch_cmd=""
        if command -v curl &>/dev/null; then
            fetch_cmd="curl -sSL https://get.docker.com | sudo sh"
        elif command -v wget &>/dev/null; then
            fetch_cmd="wget -qO- https://get.docker.com | sudo sh"
        else
            if [ "$AUTO_YES" = true ]; then
                log_message "[INFO] Neither curl nor wget found. Auto-installing curl via apt-get..."
                run_command sudo apt-get update
                run_command sudo apt-get install -y curl
                fetch_cmd="curl -sSL https://get.docker.com | sudo sh"
            else
                read -p "[WARNING] Neither curl nor wget is installed. Install curl to proceed? (y/N): " install_curl
                if [[ "$install_curl" =~ ^[Yy]$ ]]; then
                    run_command sudo apt-get update
                    run_command sudo apt-get install -y curl
                    fetch_cmd="curl -sSL https://get.docker.com | sudo sh"
                else
                    log_message "[ERROR] Cannot proceed without curl or wget."
                    exit 1
                fi
            fi
        fi

        log_message "[INFO] Downloading and executing official Docker installation script..."
        local dock_out
        dock_out=$(eval "$fetch_cmd" 2>&1)
        install_status=$?

        if [ "$(level_to_num "$LOG_LEVEL")" -le 0 ]; then
            log_message "[DEBUG] Docker Installation Script Output:"
            echo "$dock_out" | while IFS= read -r line; do
                [ -n "$line" ] && log_message "[DEBUG]   $line"
            done
        fi

        if [ "$install_status" -ne 0 ]; then
            log_message "[ERROR] Docker installation failed. Check $LOG_FILE for details."
            exit 1
        fi

        if ! command -v docker &>/dev/null; then
            log_message "[ERROR] Docker not found after installation. Check $LOG_FILE."
            exit 1
        fi

        log_message "[INFO] SUCCESS: Docker installed: $(docker --version)"
        log_message "[INFO] SUCCESS: Docker Compose installed: $(docker compose version)"
    else
        log_message "[INFO] OK: Docker already installed: $(docker --version)"
        log_message "[INFO] OK: Docker Compose: $(docker compose version)"
    fi

    log_message "[INFO] Verifying Docker group exists..."
    if ! getent group docker >/dev/null; then
        log_message "[ERROR] Docker group not found. Check $LOG_FILE."
        exit 1
    fi

    log_message "[INFO] Setting up $ACTUAL_USER for Docker..."
    if ! groups "$ACTUAL_USER" | grep -q '\bdocker\b'; then
        run_command sudo usermod -aG docker "$ACTUAL_USER"
        run_command sudo systemctl restart docker
        log_message "[INFO] Waiting for Docker daemon to be ready..."
        for i in {1..30}; do
            if systemctl is-active --quiet docker; then
                log_message "[INFO] Docker service is active."
                if sudo docker info >/dev/null 2>&1; then
                    log_message "[INFO] Docker daemon is ready."
                    break
                fi
            fi
            log_message "[INFO] Waiting for Docker daemon ($i/30)..."
            sleep 2
        done
        if ! systemctl is-active --quiet docker; then
            log_message "[ERROR] Docker service not active after waiting. Check daemon status:"
            systemctl status docker | sudo tee -a "$LOG_FILE"
            journalctl -u docker --no-pager | tail -50 | sudo tee -a "$LOG_FILE"
            log_message "[INFO] Try manually starting Docker: 'sudo systemctl start docker'"
            exit 1
        fi
        if ! sudo docker info >/dev/null 2>&1; then
            log_message "[ERROR] Cannot connect to Docker daemon as root. Check daemon status:"
            systemctl status docker | sudo tee -a "$LOG_FILE"
            journalctl -u docker --no-pager | tail -50 | sudo tee -a "$LOG_FILE"
            log_message "[INFO] Try manually starting Docker: 'sudo systemctl start docker'"
            exit 1
        fi
        log_message "[INFO] Group membership updated."
        log_message "[INFO] To use Docker without sudo, run 'newgrp docker' to apply changes in this session."
        log_message "[INFO] Alternatively, start a new terminal session or log out and back in."
        log_message "[INFO] OK: $ACTUAL_USER added to Docker group."
    else
        log_message "[INFO] OK: $ACTUAL_USER already in Docker group."
        if ! id -nG | grep -qw "docker"; then
            log_message "[INFO] Docker group not active in this session."
            log_message "[INFO] Run 'newgrp docker' to apply changes, or start a new terminal session."
            return 0
        fi
        log_message "[INFO] Testing Docker..."
        if docker run --rm hello-world >/dev/null 2>&1; then
            log_message "[INFO] SUCCESS: Docker test passed!"
        else
            log_message "[WARNING] Docker test failed. Run 'newgrp docker' to apply changes, or log out and back in."
            journalctl -u docker --no-pager | tail -50 | sudo tee -a "$LOG_FILE"
            exit 1
        fi
    fi

    log_message "[INFO] Docker installation complete."
}

# MODULE: CHECK UPDATE (Manage Docker)
check_update() {
    log_message "[INFO] Checking for Docker and Docker Compose..."
    if ! dpkg -l | grep -q docker; then
        log_message "[WARNING] Neither Docker nor Docker Compose is installed."
        return 0
    fi

    docker_ver=$(docker --version)
    compose_ver=$(docker compose version)
    log_message "[INFO] Current Docker: $docker_ver"
    log_message "[INFO] Current Docker Compose: $compose_ver"

    log_message "[INFO] Checking for updates..."
    run_command sudo apt-get update
    upgradable=$(apt list --upgradable 2>/dev/null | grep -E "docker|containerd" || true)
    if [ -z "$upgradable" ]; then
        log_message "[INFO] Docker and Docker Compose are already up-to-date."
    else
        if [ "$AUTO_YES" = false ]; then
            log_message "[INFO] Updates available:"
            echo "$upgradable" | while read -r line; do log_message "[INFO] $line"; done
            read -p "[INFO] Install updates to Docker & Docker Compose? (y/N): " update_choice
        fi
        if [[ "$AUTO_YES" = true || "$update_choice" =~ ^[Yy]$ ]]; then
            run_command sudo apt-get upgrade -y docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-ce-rootless-extras docker-buildx-plugin
            if [ $? -ne 0 ]; then
                log_message "[ERROR] Update failed. Check $LOG_FILE."
                exit 1
            fi
            new_docker_ver=$(docker --version | cut -d' ' -f3- | sed 's/,//')
            new_compose_ver=$(docker compose version | cut -d' ' -f4-)
            if [ "$docker_ver" != "Docker version $new_docker_ver" ] || [ "$compose_ver" != "Docker Compose version $new_compose_ver" ]; then
                log_message "[INFO] SUCCESS: Docker updated to $new_docker_ver"
                log_message "[INFO] SUCCESS: Docker Compose updated to $new_compose_ver"
            else
                log_message "[INFO] No version changes detected after update."
            fi
        else
            log_message "[INFO] Update installation skipped."
        fi
    fi
}

# MODULE: CHECK IMAGES (Manage Docker Images)
check_images() {
    local force_check_only="${1:-false}"
    log_message "[INFO] Scanning local Docker images against remote manifests..."
    
    local update_count=0
    local images_to_update=()
    
    for img in $(docker images --format '{{.Repository}}:{{.Tag}}' | grep -v '<none>'); do
        local local_digest
        local_digest=$(docker inspect --format='{{index .RepoDigests 0}}' "$img" 2>/dev/null | grep -o 'sha256:.*')

        local remote_digest
        remote_digest=$(docker buildx imagetools inspect "$img" 2>/dev/null | grep "^Digest:" | head -n 1 | awk '{print $2}')
        
        if [[ -z "$local_digest" && -n "$remote_digest" ]]; then
            log_message "[WARNING] $img: UPDATE AVAILABLE (Missing local mapping)"
            images_to_update+=("$img")
            ((update_count++))
        elif [[ -n "$remote_digest" && "$local_digest" != "$remote_digest" ]]; then
            log_message "[WARNING] $img: UPDATE AVAILABLE"
            log_message "[DEBUG] Local: $local_digest | Remote: $remote_digest"
            images_to_update+=("$img")
            ((update_count++))
        elif [[ -z "$remote_digest" ]]; then
            log_message "[INFO] SKIP: $img: (No remote digest found. Locally built or private?)"
        else
            log_message "[INFO] OK: $img: CURRENT"
        fi
    done
    
    if [ "$update_count" -gt 0 ]; then
        if [ "$force_check_only" = true ]; then
            log_message "[INFO] Audit complete. $update_count image(s) have available updates. Use --update-images to pull."
            return 0
        fi

        if [ "$AUTO_YES" = false ]; then
            log_message "[INFO] Options available for $update_count image(s)."
            read -p "[INFO] Pull latest versions for these images? (y/N): " pull_choice
        fi
        
        if [[ "$AUTO_YES" = true || "$pull_choice" =~ ^[Yy]$ ]]; then
            for img_to_pull in "${images_to_update[@]}"; do
                log_message "[INFO] Pulling $img_to_pull..."
                run_command sudo docker pull "$img_to_pull"
                if [ $? -eq 0 ]; then
                    log_message "[INFO] SUCCESS: $img_to_pull updated."
                else
                    log_message "[ERROR] Failed to pull $img_to_pull. Check $LOG_FILE."
                fi
            done
            log_message "[INFO] SUCCESS: Image update sequence complete."
        else
            log_message "[INFO] Image update skipped."
        fi
    else
        log_message "[INFO] SUCCESS: All local images are current."
    fi
}

# MODULE: PURGE
purge_docker() {
    log_message "[INFO] Checking for Docker and Docker Compose..."
    if dpkg -l | grep -q docker || dpkg -l | grep -q docker-compose; then
        if [ "$AUTO_YES" = false ]; then
            log_message "[WARNING] This will COMPLETELY PURGE Docker & Docker Compose."
            read -p "[WARNING] Type 'YES' to continue: " final_confirm
            [[ "$final_confirm" != "YES" ]] && { log_message "[INFO] Purge cancelled."; return 0; }
        fi

        log_message "[INFO] Stopping Docker service..."
        run_command sudo systemctl stop docker
        run_command sudo systemctl disable docker

        log_message "[INFO] Checking for lingering processes..."
        if pgrep -x "dockerd" &>/dev/null; then
            log_message "[WARNING] Killing Docker daemon..."
            run_command sudo pkill -9 dockerd
        fi

        log_message "[INFO] Uninstalling Docker and Compose packages..."
        run_command sudo apt-get update
        run_command sudo apt-get purge -y docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-ce-rootless-extras docker-buildx-plugin
        if [ $? -ne 0 ]; then
            log_message "[ERROR] Purge failed. Check $LOG_FILE."
            exit 1
        fi

        log_message "[INFO] Cleaning up Docker data..."
        run_command sudo rm -rf /var/lib/docker /var/lib/containerd ~/.docker /usr/local/bin/docker-compose

        log_message "[INFO] Removing $ACTUAL_USER from Docker group..."
        sudo gpasswd -d "$ACTUAL_USER" docker >/dev/null 2>&1 || true

        if getent group docker >/dev/null; then
            log_message "[INFO] Removing Docker group..."
            run_command sudo groupdel docker
        fi

        log_message "[INFO] Cleaning up packages..."
        run_command sudo apt-get autoremove --purge -y
        run_command sudo apt-get clean

        log_message "[INFO] SUCCESS: Docker and Docker Compose purged!"
        
        if echo "$(sudo crontab -l 2>/dev/null)" | grep -qF "/usr/local/bin/$SCRIPT_NAME --cleanup"; then
            local new_crontab=$(sudo crontab -l 2>/dev/null | grep -vF "/usr/local/bin/$SCRIPT_NAME --cleanup")
            echo "$new_crontab" | sudo crontab -
            log_message "[INFO] Remnant cron tasks removed."
        fi
        
        if [ -f "$CFG_FILE" ]; then
            sudo rm -f "$CFG_FILE"
            log_message "[INFO] Removed configuration file ($CFG_FILE)."
        fi
    else
        log_message "[INFO] OK: Nothing to purge."
    fi
}

# CLI PARSING & TUI

# Auto-deploy / update global binary on execution (if run as root from outside target path)
if [ "$EUID" -eq 0 ] && [[ "$(realpath "$0")" != "/usr/local/bin/"* ]]; then
    cp -f "$(realpath "$0")" "/usr/local/bin/$SCRIPT_NAME" 2>/dev/null || true
    chmod +x "/usr/local/bin/$SCRIPT_NAME" 2>/dev/null || true
    rm -f "/usr/local/bin/$SCRIPT_FILE_NAME" 2>/dev/null || true
fi

# Execute setup bounds
setup_dirs

do_install=false
do_purge=false
do_manage=false
initiate_install=false
do_cleanup=false
configure_cron=false
uninstall_utility_flag=false
do_check_images=false
do_update_images=false

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -y|--yes) AUTO_YES=true ;;
        -v|--version) show_versions; exit 0 ;;
        -h|--help) show_help; exit 0 ;;
        -V|--verbose) VERBOSE=true ;;
        -i|--install) do_install=true ;;
        -p|--purge) do_purge=true ;;
        -m|--manage) do_manage=true ;;
        -k|--check-images) do_check_images=true ;;
        -u|--update-images) do_update_images=true ;;
        -c|--cleanup) do_cleanup=true ;;
        -C|--configure-cron) configure_cron=true ;;
        -d|--deploy) initiate_install=true ;;
        -r|--remove) uninstall_utility_flag=true ;;
        *) log_message "[ERROR] Unknown parameter: $1"; exit 1 ;;
    esac
    shift
done

show_menu() {
    clear
    echo "=================================================="
    echo " 🐧 $UTILITY_NAME - Docker Manager ($VERSION)"
    echo "=================================================="
    echo ""
    echo " [Core Operations]"
    echo "   1. Install Docker & Docker Compose"
    echo "   2. Check and Update Docker & Docker Compose"
    echo ""
    echo " [Maintenance & Automation]"
    echo "   3. Check Local Images for Available Updates"
    echo "   4. Run Automated System Cleanup (Prune)"
    echo "   5. Configure Automated Cleanup Schedule (Cron)"
    echo ""
    echo " [Advanced & Destructive]"
    echo "   6. Purge ALL Docker Installations & Volumes"
    echo ""
    echo "   0. Exit"
    echo "--------------------------------------------------"
    echo -n "Choose an option [0-6]: "
}

if [ "$do_install" = true ] || [ "$do_purge" = true ] || [ "$do_manage" = true ] || [ "$do_check_images" = true ] || [ "$do_update_images" = true ] || [ "$do_cleanup" = true ] || [ "$configure_cron" = true ] || [ "$initiate_install" = true ] || [ "$uninstall_utility_flag" = true ]; then
    log_message "[INFO] Running $UTILITY_NAME $VERSION"
    if [ "$do_purge" = true ] && [ "$do_manage" = true ]; then
        log_message "[ERROR] Cannot use --purge and --manage together!"
        exit 1
    fi
    
    if [ "$do_install" = true ]; then
        setup_docker
    elif [ "$do_purge" = true ]; then
        purge_docker
    elif [ "$do_manage" = true ]; then
        check_update
    elif [ "$do_check_images" = true ]; then
        check_images true
    elif [ "$do_update_images" = true ]; then
        check_images false
    elif [ "$do_cleanup" = true ]; then
        perform_cleanup
    elif [ "$configure_cron" = true ]; then
        setup_cron
    elif [ "$initiate_install" = true ]; then
        install_utility
    elif [ "$uninstall_utility_flag" = true ]; then
        uninstall_utility
    fi
    exit 0
else
    while true; do
        show_menu
        read choice
        case $choice in
            1)
                log_message "[INFO] Running $UTILITY_NAME $VERSION"
                setup_docker
                ;;
            2)
                log_message "[INFO] Running $UTILITY_NAME $VERSION"
                check_update
                ;;
            3)
                log_message "[INFO] Running $UTILITY_NAME $VERSION"
                check_images false
                ;;
            4)
                log_message "[INFO] Running $UTILITY_NAME $VERSION"
                perform_cleanup
                ;;
            5)
                log_message "[INFO] Running $UTILITY_NAME $VERSION"
                setup_cron
                ;;
            6)
                log_message "[INFO] Running $UTILITY_NAME $VERSION"
                purge_docker
                ;;
            0)
                log_message "[INFO] Exiting."
                exit 0
                ;;
            *)
                log_message "[ERROR] Invalid option: $choice"
                ;;
        esac
        echo "Press any key to continue..."
        read -n 1 -s
        clear
    done
fi
